### ISSUE TITLE
Exception thrown when trying to ennumerate the sensors

### ISSUE THREAD

**Issue by core-jjavims** [NordicID/nur_sample_accsensor#1]
Hi, if you try to use the NordicID.NurApi.Net SDK it fails when you try to ennumerate the sensors calling `AccSensorEnumerate()`.

To reproduce the error is as simple as connect to your FR22 reader and call `AccSensorEnumerate()`. Also in this project it can be reproduced doing the following steps: 

1. Checkout `nur-api-5-accessory-api` branch.
2. Comment line 197 as it currently shows another error before the one we are interested in. `//statusLabel.Text = "Connected";`
3. Execute the code and connect to the FR22.
4. A NurApi exception is thrown with the following message: `NurApi error 1: Invalid command sent to module | ExecFail`

Is there any way of making this worki with the actual version or should we wait for an update?

Thanks and best regards.

**Comment by Buryyy** [comment]
Hi [core-jjavims](https://github.com/core-jjavims),

Unfortunately, this issue cannot be fixed without updating the core NordicID.NurApi.Net. However, I will prioritize this and work on a hotfix to address the problem.

Thank you for bringing this to our attention, and we appreciate your patience.

Best regards,
Buryyy

**Comment by Buryyy** [comment]
Hello @core-jjavims,

Following up on our previous discussion, I have prioritized the issue and released a [Hotfix](https://nordicid.github.io/nurapi_docs_website/versions/5.0.1.html). This update is now available in the `NordicID.NurApi.Net` 5.0.1 NuGet package.

Please note that while the error will still be logged, it can be safely ignored as the NurApi was attempting to access a feature that is not supported in the fixed readers. Additionally, the other software error has now been resolved.

Here are the related commits for your reference:
- [Commit 607cc46](https://github.com/NordicID/nur_sample_accsensor/commit/607cc46fd75d8ecb0fae0d012ef89e6f8132ead9)
- [Commit 6d70f33](https://github.com/NordicID/nur_sample_accsensor/commit/6d70f33489443c32507460ffeb8fbe38f52bc1a9)

Thank you for your patience and understanding.

Best regards,
Buryyy

**Comment by core-jjavims** [comment]
Hello @Buryyy now it works perfectly on my program too. 

Thanks and best regads!
