### ISSUE TITLE
One ToF position is not working after the last update

### ISSUE THREAD

**Issue by core-jjavims** [NordicID/nur_sample_accsensor#2]
Hi,

After the hotfix from #1 the last sensor measure can not be obtained correctly as it always returns 0.

![image](https://github.com/NordicID/nur_sample_accsensor/assets/158564424/4a3a9139-1135-4a7b-bd8e-7b944f6f0685)

As it can be seen on the image on the ToF distances the one in the bottom right is always 0, but in the previous version it displays that value. Also I would like to mention that after that position being 0 the rest of the position are moved.

How to reproduce:

1. Checkout `nur-api-5-accessory-api branch`.
2. Run the code and connect to  the reader.
3. Check the ToF values and see that the last ToF position is always 0.

Thanks and best regards.

**Comment by Buryyy** [comment]
Hi @core-jjavims !

First off, sorry for the delay!

We have investigated the issue and identified a problem in the new NUR API related to how it reads the accessory extension API commands. This issue has now been fixed. However, we are currently awaiting the licensing information for the library. Once we receive this, I will update the NUR API to include this hotfix. ETA is 1-2 working days.

Thank you for your patience!

**Comment by Buryyy** [comment]
Hi,

I wanted to update you on the NurApi licensing decision. Unfortunately, it is taking longer than expected. We are still aiming to resolve it this week. However, if we don't have the information by Friday, I will proceed with updating NurApi regardless.

Thank you for your patience.

**Comment by core-jjavims** [comment]
Hi,

@Buryyy thanks for the update.

**Comment by Buryyy** [comment]
Hi @core-jjavims,

Sorry for the delay. The api is now updated to version 5.0.2 which is including the fix.

Related commit: https://github.com/NordicID/nur_sample_accsensor/commit/78cfe0347b6a8ce7ba90d67a98e2b73f0cc14732
Release notes: https://nordicid.github.io/nurapi_docs_website/versions/5.0.2.html

**Comment by core-jjavims** [comment]
Hi,

I have tryed the new version and it is working correctly.

Thanks for the help.
